WARNING  pytest_result_log:plugin.py:122 ---------------------Start: pytest/test_fixture.py::test_2----------------------
WARNING  pytest_result_log:plugin.py:128 ----------------------End: pytest/test_fixture.py::test_2-----------------------